id: P007057
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159414
  title: བརྡ་སྤྲོད་མུ་ཐི་ལའི་ཕྲེང་བ།
  author: ''
  volumes:
    4e3a8cb2b7024096b5da9f0068eff6af:
      image_group_id: I2PD18977
      title: ''
      volume_number: 1
      total_pages: 536
ebook_metadata:
  title: བརྡ་སྤྲོད་མུ་ཐི་ལའི་ཕྲེང་བ།
  author: ''
  sku: P007057
  cover: cover.jpg
  layers:
  - pagination
